/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedOptimizerRouteImport } from './routes/_authenticated/optimizer'

const AuthenticatedOptimizerRoute = AuthenticatedOptimizerRouteImport.update({
  id: '/_authenticated/optimizer',
  path: '/optimizer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/optimizer': typeof AuthenticatedOptimizerRoute
}
export interface FileRoutesByTo {
  '/optimizer': typeof AuthenticatedOptimizerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated/optimizer': typeof AuthenticatedOptimizerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/optimizer'
  fileRoutesByTo: FileRoutesByTo
  to: '/optimizer'
  id: '__root__' | '/_authenticated/optimizer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedOptimizerRoute: typeof AuthenticatedOptimizerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated/optimizer': {
      id: '/_authenticated/optimizer'
      path: '/optimizer'
      fullPath: '/optimizer'
      preLoaderRoute: typeof AuthenticatedOptimizerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedOptimizerRoute: AuthenticatedOptimizerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
